# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup
def appodeal
  pod 'APDAdColonyAdapter', '3.0.0.1'
  pod 'BDMAdColonyAdapter', '~> 1.9.4'
  pod 'APDAppLovinAdapter', '3.0.0.1'
  pod 'APDBidMachineAdapter', '3.0.0.2' # Required
  pod 'BDMCriteoAdapter', '~> 1.9.4'
  pod 'BDMPangleAdapter', '~> 1.9.4.2'
  pod 'BDMAmazonAdapter', '~> 1.9.4.2'
  pod 'BDMSmaatoAdapter', '~> 1.9.4'
  pod 'BDMTapjoyAdapter', '~> 1.9.4'
  pod 'APDGoogleAdMobAdapter', '3.0.0.2'
  pod 'APDIABAdapter', '3.0.0.1' # Required
  pod 'BDMIABAdapter', '~> 1.9.4'
  pod 'APDIronSourceAdapter', '3.0.0.1'
  pod 'APDMetaAudienceNetworkAdapter', '3.0.0.1'
  pod 'BDMMetaAudienceAdapter', '~> 1.9.4'
  pod 'APDMyTargetAdapter', '3.0.0.1'
  pod 'BDMMyTargetAdapter', '~> 1.9.4'
  pod 'APDStackAnalyticsAdapter', '3.0.0.1' # Required
  pod 'APDUnityAdapter', '3.0.0.1'
  pod 'APDVungleAdapter', '3.0.0.1'
  pod 'BDMVungleAdapter', '~> 1.9.4'
  pod 'APDYandexAdapter', '3.0.0.1'
end
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  appodeal
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0' or comment the line with '#'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
      
        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',
        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        
      ]

    end
  end
end
